version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: leadsponge/api
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=homolog
    links:
      - db

  db:
    image: mysql:8.0.26
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=blinkdev
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/promitheus/prometheus.yml"
    command:
      - "--config.file=/etc/promitheus/prometheus.yml"
    ports:
      - "9090:9090"